### ISSUE TITLE
executeChecks SQL Server syntax error

### ISSUE THREAD

**Issue by alexharms** [darwin-eu/DrugExposureDiagnostics#10]
Hello,
I'm trying to run the CdmOnboarding package, but the DED checks raise an error (the SQL Server, actually).

R 4.2.1
CdmOnboarding 3.3.2
DrugExposureDiagnostics 1.0.10

Running with default parameters, so [this](https://github.com/darwin-eu/CdmOnboarding/blob/d1793e3014957bb107349320173820b4a4427716/R/DedChecks.R#L73) should be what's executed:
```
  dedResults <- DrugExposureDiagnostics::executeChecks(
    cdm = cdm,
    ingredients = dedIngredients$concept_id,
    checks = c("missing", "exposureDuration", "type", "route", "dose", "quantity", "diagnosticsSummary"),
    minCellCount = 5,
    sample = NULL,
    earliestStartDate = "2010-01-01"
  )
```

![image](https://github.com/user-attachments/assets/620f1812-83fc-47d9-8e97-f92e3bdc0daa)

Any help would be appreciated.

**Comment by ginberg** [comment]
@alexharms this looks similar to https://github.com/darwin-eu/CdmOnboarding/issues/12
Can you run DED in isolation like Maxim mentioned in that issue and see if that works?

**Comment by alexharms** [comment]
Thanks for the quick reply. I was able to run the code without using the CdmOnboarding package, so it's not a problem of DED.
