### ISSUE TITLE
Error - executeChecks 

### ISSUE THREAD

**Issue by anallg** [darwin-eu/DrugExposureDiagnostics#4]
Hi, 
We are running this piece of code 
```
dedResults <- DrugExposureDiagnostics::executeChecks(
            cdm = cdm,
            ingredients = c(528323, 954688, 968426,1119119, 1125315, 1139042,1140643,1154343,1550557,1703687, 40225722),
            checks = c("exposureDuration", "type", "route", "dose", "quantity", "diagnosticsSummary"),
            minCellCount = 5,
            sample = 1e+06,
            earliestStartDate = "2010-01-01"
          )

```
on our database instance in Spark, and we’re encountering an error. Below is the error we’re seeing:
![image](https://github.com/user-attachments/assets/3f25ce4c-2153-4556-8a6b-f8f5baca1f2b)

If you need any additional information to help resolve this issue, please just let me know.

**Comment by ginberg** [comment]
hi @anallg, can you try to run it using "sample = NULL"? We are still investigating the issue, but hopefully this works for now

**Comment by gargij13** [comment]
Hi,

We encountered the same error and attempted to set sample=NULL. However, this resulted in an empty output folder, with an error message indicating that the n_sample column was missing.

**Comment by ginberg** [comment]
hi @gargij13, thanks for the feedback. Ok, that's clearly a bug if sample. = NULL is not working, will work on that.
But I have made an update that hopefully will fix the executeChecks. Could you install the version from the develop branch and run executeChecks with the original sample value?
`remotes::install_github("darwin-eu/DrugExposureDiagnostics", ref = "develop")`
