### ISSUE TITLE
error with writeResultToDisk

### ISSUE THREAD

**Issue by Xintong-Li-ZnCu** [darwin-eu/DrugExposureDiagnostics#6]
We encountered the following error with  `writeResultToDisk`  with version "1.0.5". 
@anallg Could you please confirm? 
```
! Table is collected to memory as not all requested estimates are supported on the database side

Start summary of data, at 2024-10-18 11:45:22.04835

v Summary finished, at 2024-10-18 11:45:24.002946

There were 12 warnings (use warnings() to see them)

Error in stopifnot(is.character(filename), length(filename) == 1L) :

  reached elapsed time limit
```

**Comment by ginberg** [comment]
@Xintong-Li-ZnCu @anallg  this error doesn't seem specific to running writeResultToDisk. If you google at the error there are a lot of results. Could you try the possible solutions described [here](https://forum.posit.co/t/reached-elapsed-time-limit-warnings-rstudio/36647/4) 
See also [this issue](https://github.com/tidyverse/tibble/issues/1566) that Marti opened

**Comment by ginberg** [comment]
@Xintong-Li-ZnCu closing this because I haven't heard anything since my last reaction. Please reopen if you still think it is related to code in the package

**Comment by PRijnbeek** [comment]
In that case post in dev repository
