### ISSUE TITLE
executeChecks error

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu/DrugExposureDiagnostics#7]
Hi! I've realised that when executing the following lines of code (checkDrugUse.R):
```
 if (!is.null(sampleSize)) {
    drugRecordCount <- cdm[["ingredient_drug_records"]] %>%
      dplyr::tally() %>%
      dplyr::pull(.data$n)
    if (sampleSize > drugRecordCount) {
      sampleSize <- drugRecordCount
    }
  }
```

the DrugRecordCount sometimes is saved as a int64 value. Afterwards, when using DrugUtilisation::summariseDoseCoverage(), if sampleSize is an int64 value, it doesn't work (see this [issue](https://github.com/darwin-eu/DrugUtilisation/issues/617)).

I have tried adding the following line of code and seems to fix this issue:

```
 if (!is.null(sampleSize)) {
    drugRecordCount <- cdm[["ingredient_drug_records"]] %>%
      dplyr::tally() %>%
      dplyr::pull(.data$n) %>%
      as.numeric()
    if (sampleSize > drugRecordCount) {
      sampleSize <- drugRecordCount
    }
  }
```

Do you think this could be implemented? I am having some trouble with runing DrugExposureDiagnostics because of this bug!

**Comment by ginberg** [comment]
@martaalcalde can you try with the dev version:
`remotes::install_github("darwin-eu/DrugExposureDiagnostics", ref = "develop")`
We have another issue with the sampleSize in drugDose, but we haven't created a new release yet

**Comment by martaalcalde** [comment]
I've tried it, but doesn't seem to fix this!

**Comment by ginberg** [comment]
@martaalcalde can you post the error? in the develop version we are not using the sampleSize anymore in SummariseDoseCoverage https://github.com/darwin-eu/DrugExposureDiagnostics/blob/develop/R/checkDrugDose.R#L50-L53

**Comment by martaalcalde** [comment]
Now is working! I may have not installed the development version correctly before. Thank you very much for your quick response @ginberg !
